name: Build and Test

on:
  # Trigger the workflow on pull request (only for the master branch)
  # push:
  #   branches:
  #     - '**'
  #   paths-ignore:
  #     - '**/media/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/media/**'

jobs:  
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node-version: [20.x]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      - run: echo "Tests from code:"
      - run: npm test
      - run: echo "Tests from file with TARGET_FILE_PATH env variable:"
      - run: TARGET_FILE_PATH='./README.md' node index.js
